{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backend.serviceAccountName" . }}
  labels:
    app: backend
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
