{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "database.serviceAccountName" . }}
  labels:
    app: postgres
automountServiceAccountToken: {{ .Values.serviceAccount.automountToken }}
{{- end }}
