replicaCount: 3
image:
  repository: fitcart-frontend
  tag: v2.0.1
  pullPolicy: IfNotPresent
imagePullSecret: ''
serviceName: frontend
service:
  type: LoadBalancer
  port: 80
containerPort: 80
runtimeConfig:
  heroHighlightText: Progress.
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi
